### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by amirarabi** [lava/dockermail#8]
Hi
Can i To store mail config (/etc/dovecot and /etc/postfix) outside the container
I run this command but  container not run:

docker run -d -p 25:25 -p 587:587 -p 143:143 -v /srv/vmail:/srv/vmail -v /etc/dovecot:/etc/dovecot -v /etc/postfix:/etc/postfix dovecot:2.1.7

please help me, thanks

**Comment by gegere** [comment]
Greetings, you would not need to store these configurations outside of the container because the **image** will be created with the needed configurations. If you need to tweak something directly on the system you are not following best practices. It would be wise to follow best practices and have the **data container focus** on only the data and to have the **base image** focus the scripts and configurations needed for accessing the data container.

I have forked this repo [here](https://github.com/htmlgraphic/dockermail) and started to improve the build process. I have linked the connected needed data containers inside a [Makefile](https://github.com/htmlgraphic/dockermail/blob/develop/Makefile)

The IMAP server instance has also been updated to use [supervisor](https://github.com/htmlgraphic/dockermail/blob/develop/dovecot/supervisord.conf) so it can stay running on a CoreOS cluster. More improvements will come in response to the community needs.

Please have a look at the updates and see if this will work for you.
